Hw05 avatars
TetianaKabanova/nodejs-homework-rest-api pull request #4
Opened 2023-09-26 17:13 UTC by TetianaKabanova

2023-09-26 17:26 UTC, ceREAL133 requested changes

2023-09-26 17:26 UTC, ceREAL133 commented on routes/api/contacts-router.js
> +// upload.array("poster", 8) - в одному полі кілька файлів
видаліть зайві коменти

2023-09-26 17:31 UTC, TetianaKabanova commented on routes/api/contacts-router.js
> +// upload.array("poster", 8) - в одному полі кілька файлів
коментарі видалила

2023-09-27 11:09 UTC, ceREAL133 approved these changes

2023-09-28 12:07 UTC, merged